{
 "title": "Visual TOM License monitoring",
 "description": "Dashboard to monitor Visual TOM license usage",
 "tags": [
  "VTOM",
  "License",
  "templates"
 ],
 "time": { "from": "2024-06-20T22:00:00.000Z", "to": "2024-06-21T00:00:00.000Z" },
 "panels": [
  {
   "title": "Daily average executions (Last 30 days)",
   "type": "barchart",
   "description": "Red line is \"Allowed avg executions\"",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT to_char(vtdate, 'DD-mon') vtdate,CAST(vtinfos -> 'sum' -> 'nb' AS INT) \"# of execs\" FROM vt_license_counter WHERE vtdate >= CURRENT_DATE - INTERVAL '30 days'\r\nORDER BY to_char(vtdate, 'YYYYMMDD') ASC"
    },
    {
     "rawSql": "SELECT\r\n  vtvalue\r\nFROM\r\n  vt_license_entries\r\nWHERE\r\n  vtkey = 'VT-NB-EXECS'"
    }
   ]
  },
  {
   "title": "Avg daily executions for current year",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  (SUM(CAST(vtinfos -> 'sum' -> 'nb' AS INT))/(EXTRACT(DOY FROM CURRENT_DATE)))::numeric(10,0) nbexecs,\r\n        CAST((SELECT vtvalue FROM vt_license_entries WHERE vtkey='VT-NB-EXECS') AS INT) maxexecs\r\nFROM vt_license_counter\r\nWHERE date_part('year', vtdate)=date_part('year', now())"
    }
   ]
  },
  {
   "title": "Number of Jobs",
   "type": "gauge",
   "description": "Monitor the number of Jobs created compared to the license allowance.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT tab.nbjobs nbjobs,CAST(vtvalue AS INT) maxjobs FROM (SELECT COUNT(vt_core_jobs) nbjobs FROM vt_core_jobs) tab,vt_license_entries WHERE vtkey = 'VT-JOB'"
    }
   ]
  },
  {
   "title": "Number of Agents",
   "type": "gauge",
   "description": "Monitor the number of Agents used compared to the license allowance.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) nbagents,vtvalue maxagents FROM (SELECT vt_core_hosts.vtipv4,vtvalue FROM vt_core_hosts,vt_license_entries WHERE vtbdaemonstatus=16 and vtkey='VT-MACHINE' group by vtipv4,vtvalue) tab group by vtvalue"
    }
   ]
  },
  {
   "title": "Trend of executions (current year)",
   "type": "trend",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(DOY FROM dates.dt) AS vtdate,\r\n\tSUM(CAST((SELECT vtvalue FROM vt_license_entries WHERE vtkey='VT-NB-EXECS') AS INT)) OVER (ORDER BY to_char(dates.dt, 'YYYYMMDD') ASC) AS \"# of execs allowed\"\r\nFROM (\r\n\tSELECT generate_series(DATE_TRUNC('year', CURRENT_DATE), DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '1 year - 1 day', '1 day') AS dt\r\n) AS dates\r\nORDER BY to_char(dates.dt, 'YYYYMMDD') ASC;"
    },
    {
     "rawSql": "SELECT EXTRACT(DOY FROM vtdate) vtdate,\r\n\tSUM(CAST(vtinfos -> 'sum' -> 'nb' AS INT)) OVER (ORDER BY to_char(vtdate, 'YYYYMMDD') ASC) \"# of execs\"\r\nFROM vt_license_counter\r\nWHERE vtdate >= DATE_TRUNC('year', CURRENT_DATE)\r\nORDER BY to_char(vtdate, 'YYYYMMDD') ASC"
    },
    {
     "rawSql": "SELECT EXTRACT(DOY FROM dates.dt) AS vtdate,\r\n\t(SELECT SUM(CAST(vtinfos -> 'sum' -> 'nb' AS INT)) FROM vt_license_counter\r\n\tWHERE vtdate >= DATE_TRUNC('year', CURRENT_DATE)) + SUM(\r\n\t\tCAST((SELECT (SUM(CAST(vtinfos -> 'sum' -> 'nb' AS INT))/(EXTRACT(DOY FROM CURRENT_DATE)))::numeric(10,0) FROM vt_license_counter \tWHERE vtdate >= DATE_TRUNC('year', CURRENT_DATE)) AS INT)) OVER (ORDER BY to_char(dates.dt, 'YYYYMMDD') ASC) AS \"Trend based on current year\"\r\nFROM (\r\n\tSELECT generate_series( CURRENT_DATE, DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '1 year - 1 day', '1 day') AS dt\r\n) AS dates\r\nORDER BY to_char(dates.dt, 'YYYYMMDD') ASC;"
    },
    {
     "rawSql": "SELECT EXTRACT(DOY FROM dates.dt) AS vtdate,\r\n\t(SELECT SUM(CAST(vtinfos -> 'sum' -> 'nb' AS INT)) FROM vt_license_counter\r\n\tWHERE vtdate >= DATE_TRUNC('year', CURRENT_DATE)) + SUM(\r\n\t\tCAST((SELECT (SUM(CAST(vtinfos -> 'sum' -> 'nb' AS INT))/30)::numeric(10,0) FROM vt_license_counter \tWHERE vtdate >= CURRENT_DATE - INTERVAL '30 days') AS INT)) OVER (ORDER BY to_char(dates.dt, 'YYYYMMDD') ASC) AS \"Trend based on last 30 days\"\r\nFROM (\r\n\tSELECT generate_series( CURRENT_DATE, DATE_TRUNC('year', CURRENT_DATE) + INTERVAL '1 year - 1 day', '1 day') AS dt\r\n) AS dates\r\nORDER BY to_char(dates.dt, 'YYYYMMDD') ASC;"
    }
   ]
  },
  {
   "title": "License Expiration",
   "type": "table",
   "description": "Expiration of Visual TOM license.   \nContact Absyss support if end is close",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT vtnbday || ' days left (' || DATE(vtend) || ')'  as \"License\"\r\nFROM vt_license_entries \r\nLIMIT 1"
    }
   ]
  }
 ]
}